### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by rrslssr** [fering3/MMM-JEOPARDY-Enhanced#1]
I am having no luck installing the MMM on a new system.-Jeopardy-Enhanced module on a new system
Following is the sequence of steps so far:

Using a new Raspberry Pi 4 Model B running Raspberry Pi OS (64-bit) Devian version 12
Setup WiFi and ssh in the Raspberry Pi Imager to allow remote access
Used @sdetweil's installation script to install MagicMirror
Verified that MagicMirror works in it's default configuration (yeah)
Setup VNC to allow remote access beyond the simple terminal (my personal preference)
Followed the instructions for installation and editing config.js
Below is what I recieve on the terminal during testing:

[12.11.2023 13:08.54.010] [ERROR] (node:16562) UnhandledPromiseRejectionWarning: Error: Cannot find module 'request'
Require stack:
- /home/rrslssr/MagicMirror/modules/MMM-JEOPARDY/node_helper.js
- /home/rrslssr/MagicMirror/js/app.js
- /home/rrslssr/MagicMirror/js/electron.js
- /home/rrslssr/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at node:internal/modules/cjs/loader:1084:15
    at Function.<anonymous> (node:electron/js2c/browser_init:2:117576)
    at Module._resolveFilename (/home/rrslssr/MagicMirror/node_modules/module-alias/index.js:49:29)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/rrslssr/MagicMirror/modules/MMM-JEOPARDY/node_helper.js:8:17)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at loadModule (/home/rrslssr/MagicMirror/js/app.js:180:19)
(Use `electron --trace-warnings ...` to show where the warning was created)
[12.11.2023 13:08.54.011] [ERROR] (node:16562) UnhandledPromiseRejectionWarning: Unhandled promise rejection. 
This error originated either by throwing inside of an async function without a catch block, or by rejecting a 
promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag 
`--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

Any assistance would be appreciated.

**Comment by sdetweil** [comment]
>Cannot find module 'request

see https://forum.magicmirror.builders/topic/15778/fix-for-black-screen-in-2-16-and-later
